name: taxiapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.27
  location: 3.0.0
  flutter_dash: ^0.0.1
  dotted_border: ^1.0.5
  maps_curved_line: ^0.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/hambergon_icon.png
    - images/girl_dp.jpg
    - images/locicon.png
    - images/home_icon.png
    - images/myoffice_icon.png
    - images/hamber2.png
    - images/home_pink.png
    - images/loc_white.png
    - images/office_pink.png
    - assets/map_style.txt
    - images/car_icon.png
    - images/navigation_curve.png
    - images/rating.png
    - images/right_ab.png
    - images/star.png
    - images/invite.png
    - images/family.png
    - images/profile.png
    - images/sign_out.png
    - images/invite_arrow.png
    - images/destination_home.png
    - images/destination_work.png
    - images/loc_ty.png
    - images/ellipse_payment.png
    - images/master_card.png
    - images/check_icon.png
    - images/promo.png
    - images/car_1.png
    - images/car_2.png
    - images/back_icon.png
    - images/cross_white.png
    - images/rting_blank.png
    - images/your_trip_call.png
    - images/loc_trip.png
    - images/clock_trip.png
    - images/curve_profile_final.png
    - images/edit.png
    - images/mail.png
    - images/button_back.png
    - images/custom_marker_back.png
    - images/map_shape.png
    - images/home_shape_map.png
    - images/map_oval.png
    - images/car_icon_map.png
  fonts:
    - family: GilroyBold
      fonts:
        - asset: fonts/gilroy_bold.otf

    - family: GilroyLight
      fonts:
        - asset: fonts/gilroy_light.otf

    - family: GilroySemibold
      fonts:
        - asset: fonts/gilroy_semibold.otf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
